"""Gate 1 integrated development platform control plane."""

__version__ = "0.1.0"

STATUS_AUTOMATED_PASS = "GATE_1_AUTOMATED_PASS"
STATUS_AUTOMATED_PARTIAL = "GATE_1_AUTOMATED_PARTIAL"
STATUS_SOFTWARE_READY = "SOFTWARE_EVIDENCE_READY"
STATUS_PHYSICAL_PENDING = "PHYSICAL_EVIDENCE_PENDING"
STATUS_GATE_1_PASS = "GATE_1_PASS"  # prohibited without accepted physical evidence
STATUS_FAIL = "GATE_1_SOFTWARE_FAIL"
