schema_version: 1.1.0
updated_at_utc: '2026-08-08T20:56:59Z'
continuation: VI
accepted_main_sha_field_kit: 2d257be6eb19b8237bf681b40f89275492fbd359
accepted_main_sha_device_os: 12ca8591202f59fdff962a4460323c6cfd67238d
campuses: 7
campus_configs: PARTIAL
fleet: NOT_PRODUCTION
support: INCOMPLETE
status: DIGITAL_PARTIAL_EXTERNAL_REQUIRED_FOR_LIVE_CAMPUSES
