schema_version: 1.1.0
updated_at_utc: '2026-08-08T19:43:23Z'
continuation: IV
accepted_main_sha_field_kit: 7ebbe27bbae6980f0db8b5c14b39f2767b448128
accepted_main_sha_device_os: a4c17d298c6f4b769c96632646425c9168e3ef98
campuses: 7
campus_configs: PARTIAL
fleet: NOT_PRODUCTION
support: INCOMPLETE
status: DIGITAL_PARTIAL_EXTERNAL_REQUIRED_FOR_LIVE_CAMPUSES
